image: node:16

pipelines:
   pull-requests:
    "**":
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm run test
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npm run lint
            caches:
              - node
